### ISSUE TITLE
The malloc problem with NDN-RIOT and how to communicate with computer

### ISSUE THREAD

**Issue by liyue75** [named-data-iot/ndn-lite-over-riot#2]
请问，README里说的“However, the RIOT is one-way malloc() thus the allocated buffer never be freed.“是什么意思？
是NDN-RIOT里没有调用free吗？还是说RIOT的malloc和free有问题，不能释放内存？
还有，如果我想用一块RIOT系统的板子（比如stm32f4）运行ndn-lite-over-riot，和电脑端进行ndn通信，我该怎么做？是在嵌入式板子上用ndn-lite提供的api写一个程序吗，电脑端呢？并且一次传输的数据不能太多（README里说不支持fragment）。

**Comment by zjkmxy** [comment]
> 请问，README里说的“However, the RIOT is one-way malloc() thus the allocated buffer never be freed.“是什么意思？
> 是NDN-RIOT里没有调用free吗？还是说RIOT的malloc和free有问题，不能释放内存？

記憶體空間分配之後不會被釋放。參https://doc.riot-os.org/group__oneway__malloc.html 。RIOT的free函式預設無操作。

> 还有，如果我想用一块RIOT系统的板子（比如stm32f4）运行ndn-lite-over-riot，和电脑端进行ndn通信，我该怎么做？是在嵌入式板子上用ndn-lite提供的api写一个程序吗，电脑端呢？并且一次传输的数据不能太多（README里说不支持fragment）。

@tianyuan129

**Comment by liyue75** [comment]
@zjkmxy 感谢
